//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSWebMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBLMSEntities : DbContext
    {
        public DBLMSEntities()
            : base("name=DBLMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEFECT> DEFECTS { get; set; }
        public virtual DbSet<LOG> LOGS { get; set; }
        public virtual DbSet<PENALTy> PENALTIES { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONS { get; set; }
        public virtual DbSet<PRODUCTPLAN> PRODUCTPLANs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<SHIFT> SHIFTS { get; set; }
        public virtual DbSet<SHOP> SHOPS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<USERSIMAGE> USERSIMAGES { get; set; }
        public virtual DbSet<VERIFICATION> VERIFICATIONs { get; set; }
    }
}
