//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int ID { get; set; }
        public string Form { get; set; }
        public string Operation { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string IP { get; set; }
        public string Line { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
