//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTPLAN
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> Plan { get; set; }
        public Nullable<int> Actual { get; set; }
        public Nullable<int> OK { get; set; }
        public Nullable<int> NG { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Defect_1 { get; set; }
        public Nullable<int> Defect_2 { get; set; }
        public Nullable<int> Defect_3 { get; set; }
        public Nullable<int> Defect_4 { get; set; }
        public Nullable<int> Defect_5 { get; set; }
        public Nullable<int> DownTime { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ShiftID { get; set; }
    
        public virtual SHIFT SHIFT { get; set; }
    }
}
